# Generated by Django 1.11.17 on 2019-01-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menu.Menu"
            ),
        ),
    ]
