# Generated by Django 1.11.17 on 2019-01-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_meal_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatePlate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_name",
            field=models.CharField(default="Sunday Brunch", max_length=200),
        ),
        migrations.AddField(
            model_name="menu",
            name="servings",
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="lateplate",
            name="meal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menu.Meal"
            ),
        ),
    ]
