# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190103_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateplate',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
