# Generated by Django 2.1.11 on 2022-01-07 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import menu.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0007_auto_20191021_0244"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealDayTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        choices=[
                            (0, menu.models.Weekday(0)),
                            (1, menu.models.Weekday(1)),
                            (2, menu.models.Weekday(2)),
                            (3, menu.models.Weekday(3)),
                            (4, menu.models.Weekday(4)),
                            (5, menu.models.Weekday(5)),
                            (6, menu.models.Weekday(6)),
                        ]
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("BRK", menu.models.MealTime("BRK")),
                            ("BRU", menu.models.MealTime("BRU")),
                            ("LUN", menu.models.MealTime("LUN")),
                            ("DIN", menu.models.MealTime("DIN")),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AutoLatePlate",
        ),
        migrations.RemoveField(
            model_name="lateplate",
            name="meal",
        ),
        migrations.AddField(
            model_name="meal",
            name="deleted_auto_lateplates",
            field=models.ManyToManyField(
                blank=True,
                related_name="deleted_auto_lateplate_meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="manual_lateplates",
            field=models.ManyToManyField(
                blank=True,
                related_name="manual_lateplate_meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mealrating",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mealrating",
            name="rating",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="servings",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.DeleteModel(
            name="LatePlate",
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_day_time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="menu.MealDayTime",
            ),
        ),
    ]
