# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('class_year', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=20, null=True)),
                ('bio', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
