# Generated by Django 3.2.11 on 2022-01-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_auto_20220112_0448"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("caption", models.TextField(blank=True)),
                ("date", models.DateField(null=True, blank=True)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
        ),
    ]
