# Generated by Django 3.2.11 on 2022-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_gallerycontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerycontent",
            options={"ordering": ["gallery_order"]},
        ),
        migrations.AddField(
            model_name="gallerycontent",
            name="gallery_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
