# Generated by Django 4.0.4 on 2023-01-15 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_auto_20220522_1640"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plushie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.member"
                    ),
                ),
            ],
        ),
    ]
