# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=20, null=True)),
                ('bio', models.TextField(null=True)),
                ('image_loc', models.CharField(max_length=100)),
            ],
        ),
    ]
