# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_loc',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
