# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_member_image_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_loc',
        ),
    ]
