# Generated by Django 3.2.11 on 2022-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220107_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=255),
        ),
    ]
